name: Build

on: [pull_request, push]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC 14
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 200
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 200

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

