name: Build and test with sanitizers

on: [ pull_request, push ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ASan
            cmake-flags: -DCMAKE_CXX_FLAGS="-fsanitize=address -fno-omit-frame-pointer"
          - name: UBSan
            cmake-flags: -DCMAKE_CXX_FLAGS="-fsanitize=undefined -fno-omit-frame-pointer"

    name: ${{ matrix.name }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 all
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 200
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 200
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{matrix.cmake-flags}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: ctest --test-dir ${{github.workspace}}/build -C ${{env.BUILD_TYPE}} --output-on-failure
